# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

variables:
- group: Passwords
- group: SoftwareVersions

parameters:
   - name: version
     displayName: Plugin version

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git
    ref: master

jobs:
- ${{ if contains(variables['Build.SourceBranch'], 'release/') }}:
  - job: Generate_Release
    pool:
      vmImage: $(ubuntuVersion)
    steps:
      - template: azure/common-steps.yaml

      - task: NodeTool@0
        inputs:
          versionSource: 'spec' 
          versionSpec: $(nodeVersion)

      - bash: |
          echo -e "\n[+] Installing NPM version $(npmVersion)\n"
          npm install -g $(npmVersion)

          currentBranch=$(echo $(Build.SourceBranch) | cut -d "/" -f 3,4)
          echo "##vso[task.setvariable variable=currentBranch]$(echo $currentBranch)"
          echo "##vso[task.setvariable variable=version]$(echo ${{ parameters.version }})"
          
          echo -e "\n[+] Variables:"
          echo -e "\t[+] Plugin version: ${{ parameters.version }}"
          echo -e "\t[+] NPM CLI version: $(npm --version)"
          echo -e "\t[+] Current branch: $currentBranch"

          echo -e "\n[+] Setting git remote credentials\n"
          git remote set-url origin https://situmops:$(github_token)@github.com/$(Build.Repository.Name).git
          cat .git/config

        displayName: Initial Vars & Configs

      - bash: |

          echo -e "\n[+] Setting NPM version to $(version)"
          npm version $(version) --no-git-tag-version

          echo -e "\n[+] Setting git to push NPM version\n"
          git config --global user.email "sistemas@situm.es"
          git config --global user.name "Situmops"

          echo -e "\n[+] Fetch branches \n"
          git fetch

          echo -e "\n[+] Changing to $(currentBranch)"
          git checkout $(currentBranch)

          echo -e "\n[+] Add,Commit and Push to $(currentBranch)"
          git commit -am "Setting the NPM version to $(version)"
          git push --set-upstream origin $(currentBranch)
          git push
        displayName: Make changes


      - template: azure-templates/publish_release.yml@sys_kubernetes_templates
        parameters:
          bitbucket:
            bitbucket_user: situmops
          system: "N/A"
          server: "github"
          mergeBranches:
            - "master-test"

      - bash: |
          echo -e "\n[+] Fetch all branches\n"
          git fetch
      
          echo -e "\n[+] Checkout and Pull to master branch\n"
          git checkout master
          git pull origin master
      
          echo -e "\n[+] Configure NPM login"
          echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > ~/.npmrc
      
          echo -e "\n[+] Publish NPM packages"
          npm publish 
      
        displayName: NPM publish
